version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: german-teaching-frontend
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: german-teaching-backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend/src:/app/src
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/germandb
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: german-teaching-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: germandb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: 