services:
  db:
      image: postgres:14-alpine
      container_name: german_teaching_db
      environment:
              POSTGRES_USER: ${POSTGRES_USER:-gauva}
              POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gauva}
              POSTGRES_DB: ${POSTGRES_DB:-appdb}
      volumes:
        - ./database:/docker-entrypoint-initdb.d
        - pgdata:/var/lib/postgresql/data
      ports:
          - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: german_app_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-appdb}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-gauva}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-gauva}
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true
      SPRING_FLYWAY_BASELINE_VERSION: 1
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app

volumes:
  pgdata: